spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: arsenal

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
